version: '2'
services:
    gate:
        build: gate
        image: lappsgrid/gate   
        ports:
            - "8080:8080"
    stanford:
        build: stanford
        image: lappsgrid/stanford
        ports:
            - "8080:8080"
    lingpipe:
        build: lingpipe
        image: lappsgrid/lingpipe
        ports:
            - "8080:8080"
    masc:
        build: masc
        image: lappsgrid/masc
        ports:
            - "8080:8080"
    oaqa:
        build: oaqa
        image: lappsgrid/oaqa
        ports:
            - "8080:8080"
    galaxy:
        build: galaxy
        image: lappsgrid/galaxy
        ports: 
            - "80:8000"
        depends_on:
            - gate
            - stanford
            - lingpipe
            - masc
            - oaqa
        links:
            - gate
            - stanford
            - lingpipe
            - masc
            - oaqa
            